# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cbefeedb0ffd396f3bcd60ff5a504ca258ac7fa6e3354bf028e8504ef37872c304c7cec8b0db81e61f0a2c3f4c8b401c3c408386f748d3d2510038cccb95167

test:
  secret_key_base: e1aa96206e6905990cb1a5d65f0b015393f78930a30a2fd755f613e2a58bb1932af6ff34deb39b59e4561ccea263c764cf92a545d71b1e3633ed16696fdacbdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
